# Generated by Django 2.0.4 on 2018-05-15 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pipelineconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='pipeline_conf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.PipelineConfiguration'),
            preserve_default=False,
        ),
    ]
