# Generated by Django 2.0.4 on 2018-05-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_session_pipeline_conf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='pipeline_id',
        ),
    ]
