# Generated by Django 2.0.4 on 2018-05-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180515_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='some_identifier',
            field=models.CharField(max_length=255),
        ),
    ]
