# Generated by Django 2.0.4 on 2018-06-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180516_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='session',
            name='pipeline_conf',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='PipelineConfiguration',
        ),
    ]
