# Generated by Django 2.0.4 on 2018-06-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('running', 'running'), ('finished', 'finished')], default='unknown', max_length=20),
        ),
    ]
