# Generated by Django 2.0.4 on 2018-06-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='pipeline_respone',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
