# Generated by Django 2.0.4 on 2018-06-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_session_pipeline_respone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='session',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('started', 'started')], default='unknown', max_length=20),
        ),
    ]
