# Generated by Django 2.0.4 on 2018-06-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180625_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('started', 'started'), ('failure', 'failure')], default='started', max_length=20),
        ),
    ]
