# Generated by Django 2.0.4 on 2018-06-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_session_test_json_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='test_JSON_field',
        ),
    ]
