# Generated by Django 2.0.4 on 2018-06-26 12:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_session_test_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='test_JSON_field',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
