# Generated by Django 2.0.4 on 2018-06-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_session_test_json_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='avg_freq_step',
        ),
        migrations.RemoveField(
            model_name='session',
            name='avg_time_step',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='session',
            name='demix_freq_step',
        ),
        migrations.RemoveField(
            model_name='session',
            name='demix_sources',
        ),
        migrations.RemoveField(
            model_name='session',
            name='demix_time_step',
        ),
        migrations.RemoveField(
            model_name='session',
            name='description',
        ),
        migrations.RemoveField(
            model_name='session',
            name='do_demix',
        ),
        migrations.RemoveField(
            model_name='session',
            name='parset',
        ),
        migrations.RemoveField(
            model_name='session',
            name='pipeline_respone',
        ),
        migrations.RemoveField(
            model_name='session',
            name='select_NL',
        ),
        migrations.RemoveField(
            model_name='session',
            name='status',
        ),
        migrations.RemoveField(
            model_name='session',
            name='test_JSON_field',
        ),
    ]
