# Generated by Django 2.0.4 on 2018-06-26 13:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180626_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='config',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
