# Generated by Django 2.0.4 on 2018-06-26 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_session_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='session',
            name='pipeline',
            field=models.CharField(default='sksp', max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='pipeline_respone',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('started', 'started'), ('failure', 'failure')], default='unknown', max_length=20),
        ),
    ]
