# Generated by Django 2.0.4 on 2018-06-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180627_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='pipeline_version',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
