# Generated by Django 2.0.4 on 2018-06-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_session_pipeline_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='observation',
            field=models.CharField(max_length=100000),
        ),
    ]
